{
 "title": "PostgreSQL Overview",
 "tags": [
  "pgsql",
  "postgres",
  "postgresql"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(sql_pg_postmaster_uptime, host)"
   },
   { "name": "job_name", "query": "sql_exporter" },
   {
    "name": "database",
    "query": "label_values(sql_pg_database_size{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]{4}\"}, datname)"
   }
  ]
 },
 "panels": [
  {
   "title": "INSTANCE UPTIME",
   "type": "singlestat",
   "description": "Number of seconds since last instance start",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "sql_pg_postmaster_uptime{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\"}"
    }
   ]
  },
  {
   "title": "REPLICATION LAG",
   "type": "singlestat",
   "description": "Replication delay in seconds",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "sql_pg_stat_replication_lag{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\"}"
    }
   ]
  },
  {
   "title": "LOAD AVERAGE 1 MIN",
   "type": "singlestat",
   "description": "Load average (last 1 minute)",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sql_pg_os_getloadavg{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", col=\"load_avg_1min\"}"
    }
   ]
  },
  {
   "title": "LOAD AVERAGE 5 MIN",
   "type": "singlestat",
   "description": "Load average (last 5 minutes)",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sql_pg_os_getloadavg{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", col=\"load_avg_5min\"}"
    }
   ]
  },
  {
   "title": "LOAD AVERAGE 15 MIN",
   "type": "singlestat",
   "description": "Load average (last 15 minutes)",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sql_pg_os_getloadavg{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", col=\"load_avg_15min\"}"
    }
   ]
  },
  {
   "title": "SWAP USAGE",
   "type": "singlestat",
   "description": "Swap usage in bytes",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sql_pg_psutil_swap_memory{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", col=\"used\"}"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "graph",
   "description": "CPU usage percents",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "sql_pg_psutil_cpu_times_percent{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", col!=\"total\"}",
     "legendFormat": "{{ col }}"
    }
   ]
  },
  {
   "title": "MEMORY USAGE",
   "type": "graph",
   "description": "Virtual memory usage",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sql_pg_psutil_virtual_memory{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", col!~\"(total|percent)\"}",
     "legendFormat": "{{ col }}"
    },
    {
     "expr": "sql_pg_psutil_swap_memory{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", col=\"used\"}",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "DISK I/O USAGE",
   "type": "graph",
   "description": "Disk i/o usage",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / second" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_psutil_disk_io_counters{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\"}[1m])",
     "legendFormat": "{{ col }}"
    }
   ]
  },
  {
   "title": "NETWORK I/O USAGE",
   "type": "graph",
   "description": "Network i/o usage",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / second" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_psutil_net_io_counters{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\"}[1m])",
     "legendFormat": "{{ col }}"
    }
   ]
  },
  {
   "title": "ANOMALIES",
   "type": "graph",
   "description": "Summary of Instance errors / conflicts / anomalies",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "anomalies" }
   ],
   "targets": [
    {
     "expr": "increase(sql_pg_current_logfile_errors{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\"}[1m])",
     "legendFormat": "{{ col }}"
    },
    {
     "expr": "increase(sql_pg_stat_archiver{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", col=\"failed_wal\"}[1m])",
     "legendFormat": "{{ col }}"
    },
    {
     "expr": "sql_pg_replication_slots{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\"}",
     "legendFormat": "{{ col }}"
    },
    {
     "expr": "sql_pg_stat_database_conflicts{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}",
     "legendFormat": "{{ datname }} {{ col }}"
    },
    {
     "expr": "sql_pg_prepared_xacts{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}",
     "legendFormat": "{{ datname }} {{ col }}"
    },
    {
     "expr": "sum by (database) (sql_pg_stat_user_tables_orphaned{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", database=~\"[[database]]\"})",
     "legendFormat": "{{ database }} orphaned_tables"
    },
    {
     "expr": "count by (database) (sql_pg_stat_user_indexes_redundant{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", database=~\"[[database]]\"})",
     "legendFormat": "{{  database }} redundant_indexes"
    },
    {
     "expr": "sql_pg_stat_user_indexes_invalid{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", database=~\"[[database]]\"}",
     "legendFormat": "{{ database }} {{ col }}"
    },
    {
     "expr": "sql_pg_trigger_disabled{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", database=~\"[[database]]\"}",
     "legendFormat": "{{ database }} {{ col }}"
    }
   ]
  },
  {
   "title": "DATABASE SIZE",
   "type": "graph",
   "description": "Size of instance databases",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "decbytes", "label": "size" }
   ],
   "targets": [
    {
     "expr": "sql_pg_database_size{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "CONNECTIONS",
   "type": "graph",
   "description": "Number of connections of all states per database",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "sql_pg_stat_activity_backends{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\", col!=\"max_connections\"}",
     "legendFormat": "{{ datname }} {{ col }}"
    },
    {
     "expr": "max(sql_pg_stat_activity_backends{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", col=~\"max_connections\"})",
     "legendFormat": "max_connections"
    }
   ]
  },
  {
   "title": "AVERAGE RESPONSE TIME",
   "type": "graph",
   "description": "Average statements response time per database",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "sql_pg_stat_statements_avg_time{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}",
     "legendFormat": "{{  datname }}"
    }
   ]
  },
  {
   "title": "LOCKS BY TYPE",
   "type": "graph",
   "description": "Number of locks by type per database",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "locks" }
   ],
   "targets": [
    {
     "expr": "sql_pg_locks_type{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}",
     "legendFormat": "{{ datname }} {{ type }}"
    }
   ]
  },
  {
   "title": "LOCKS BY MODE",
   "type": "graph",
   "description": "Number of locks by mode per database",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "locks" }
   ],
   "targets": [
    {
     "expr": "sql_pg_locks_mode{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}",
     "legendFormat": "{{ datname }} {{ mode }}"
    }
   ]
  },
  {
   "title": "CACHE BUFFERS",
   "type": "graph",
   "description": "Amount of shared memory used per database",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes", "label": "buffers" }
   ],
   "targets": [
    {
     "expr": "(sql_pg_buffercache_pages{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\", col!=\"max\"}) * 8192",
     "legendFormat": "{{ datname }} {{ col }}"
    },
    {
     "expr": "max((sql_pg_buffercache_pages{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", col=\"max\"}) * 8192)",
     "legendFormat": "max_buffers"
    }
   ]
  },
  {
   "title": "CACHE HIT RATIO",
   "type": "graph",
   "description": "Memory hit ratio per database",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "percent", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "sql_pg_stat_database_cache_hit_ratio{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "SHARED MEMORY / OS CACHE / DISK HIT",
   "type": "graph",
   "description": "Ratio of shared memory, kernel cache or disk device read per database",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "percent", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "sql_pg_stat_kcache_hit_ratio{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}",
     "legendFormat": "{{ datname }} {{ col }}"
    }
   ]
  },
  {
   "title": "TUPLES WRITTEN RATE",
   "type": "graph",
   "description": "Number of tuples inserted / updated / deleted per second per database",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "tuples / second" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_stat_database_tuples{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}[1m])",
     "legendFormat": "{{ datname }} {{ col }}"
    }
   ]
  },
  {
   "title": "LONG TRANSACTIONS",
   "type": "graph",
   "description": "Longest statement duration per database",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "sql_pg_stat_activity_max_xact_age{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "TRANSACTION RATE",
   "type": "graph",
   "description": "Number of transactions commited / rolledback per second per database",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "ops", "label": "transactions / second" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_stat_database_transactions{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}[1m])",
     "legendFormat": "{{ datname }} {{ col }}"
    }
   ]
  },
  {
   "title": "TEMPORARY FILES RATE",
   "type": "graph",
   "description": "Size of temp files per second per database",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / second" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_stat_database_temp_files{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\", col=\"temp_bytes\"}[1m])",
     "legendFormat": "{{ datname }} "
    }
   ]
  },
  {
   "title": "TOP TABLES BY SEQUENTIAL TUPLE READS",
   "type": "graph",
   "description": "Top tables with the biggest number of tuples read by sequential scan",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "tuples / second" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_stat_user_tables_sequential_tuple_read{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}[1m])",
     "legendFormat": "{{ datname }} {{ relname }}"
    }
   ]
  },
  {
   "title": "DISK READ / WRITE RATE",
   "type": "graph",
   "description": "Number of bytes read / written per second per database",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / second" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_stat_kcache_total_bytes{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}[1m])",
     "legendFormat": "{{ datname }} {{ col }}"
    }
   ]
  },
  {
   "title": "WRITE AHEAD LOG RATE",
   "type": "graph",
   "description": "Amount of write-ahead log in bytes per second",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / second" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_wal_rate{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\"}[1m])",
     "legendFormat": "wal writing"
    },
    {
     "expr": "increase(sql_pg_stat_archiver{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", col=\"archived_wal\"}[1m])",
     "legendFormat": "wal archiving"
    }
   ]
  },
  {
   "title": "WRITE AHEAD LOG DIRECTORY",
   "type": "graph",
   "description": "Size and amount of files in write ahead log directory",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "decbytes", "label": "wal size" }
   ],
   "targets": [
    {
     "expr": "sql_pg_ls_waldir{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", col=\"wal_size\"}",
     "legendFormat": "wal size"
    },
    {
     "expr": "sql_pg_ls_waldir{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", col=\"wal_count\"}",
     "legendFormat": "wal count"
    }
   ]
  },
  {
   "title": "CHECKPOINTS RATE",
   "type": "graph",
   "description": "Checkpoint process frequency",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "checkpoints / minute" }
   ],
   "targets": [
    {
     "expr": "increase(sql_pg_stat_bgwriter_checkpoints{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\"}[1m])",
     "legendFormat": "{{ col }}"
    }
   ]
  },
  {
   "title": "BUFFERS WRITTEN RATE",
   "type": "graph",
   "description": "Number of buffers written per second by background writer / checkpointer",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "buffers / second" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_stat_bgwriter_buffers{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\"}[1h])",
     "legendFormat": "{{ col }}"
    }
   ]
  },
  {
   "title": "AUTOVACUUM WORKERS",
   "type": "graph",
   "description": "Number of autovacuum workers used per database",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "autovacuum workers" }
   ],
   "targets": [
    {
     "expr": "sql_pg_stat_activity_autovacuum_workers{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\", col!=\"max\"}",
     "legendFormat": "{{ datname }} {{ col }}"
    },
    {
     "expr": "max(sql_pg_stat_activity_autovacuum_workers{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", col=\"max\"})",
     "legendFormat": "max_autovacuum_workers"
    }
   ]
  },
  {
   "title": "TRANSACTIONS BEFORE WRAPAROUND VACUUM",
   "type": "graph",
   "description": "Number of transactions left before wraparound vacuum",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "transactions left" }
   ],
   "targets": [
    {
     "expr": "sql_pg_database_xacts_before_wraparound_vacuum{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "TOP TABLES BY AUTOVACUUM",
   "type": "graph",
   "description": "Top tables with the biggest number of autovacuum occurred",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "total autovacuums" }
   ],
   "targets": [
    {
     "expr": "sql_pg_stat_user_tables_autovacuum_count{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", database=~\"[[database]]\"}",
     "legendFormat": "{{ database }} {{ relname }}"
    }
   ]
  },
  {
   "title": "TOP TABLES BY INSERTED TUPLES",
   "type": "graph",
   "description": "Top tables with the biggest number of inserted tuples",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "tuples / second" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_stat_user_tables_insert{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}[1m])",
     "legendFormat": "{{ datname }} {{ relname }}"
    }
   ]
  },
  {
   "title": "TOP TABLES BY UPDATED TUPLES",
   "type": "graph",
   "description": "Top tables with the biggest number of updated tuples",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "tuples / second" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_stat_user_tables_update{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}[1m])",
     "legendFormat": "{{ datname }} {{ relname }}"
    }
   ]
  },
  {
   "title": "TOP TABLES BY DELETED TUPLES",
   "type": "graph",
   "description": "Top tables with the biggest number of deleted tuples",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "tuples / second" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_stat_user_tables_delete{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}[1m])",
     "legendFormat": "{{ datname }} {{ relname }}"
    }
   ]
  },
  {
   "title": "TOP LONGEST QUERIES",
   "type": "graph",
   "description": "Top statements by duration per database",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "dtdurationms", "label": "average time" }
   ],
   "targets": [
    {
     "expr": "sql_pg_stat_statements_duration{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}",
     "legendFormat": "{{ datname }} : {{ query }}"
    }
   ]
  },
  {
   "title": "TOP FREQUENT QUERIES",
   "type": "graph",
   "description": "Top statements by executions per database",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "calls / second" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_stat_statements_frequency{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}[1m])",
     "legendFormat": "{{ datname }} : {{ query }}"
    }
   ]
  },
  {
   "title": "TOP QUERIES BY RESULT ROWS",
   "type": "graph",
   "description": "Top statements by retrieved / affected rows per database",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short", "label": "rows / second" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_stat_statements_result_rows{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}[1m])",
     "legendFormat": "{{ datname }} : {{ query }}"
    }
   ]
  },
  {
   "title": "TOP QUERIES BY DISK READS",
   "type": "graph",
   "description": "Top statements by disk device reads per database",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / second" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_stat_statements_disk_hit{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}[1m])",
     "legendFormat": "{{ datname }} : {{ query }}"
    }
   ]
  },
  {
   "title": "TOP QUERIES BY CPU USAGE",
   "type": "graph",
   "description": "Top statements by CPU utilization per database",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "percent", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "sql_pg_stat_statements_cpu_usage{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}",
     "legendFormat": "{{ datname }} : {{ query }}"
    }
   ]
  },
  {
   "title": "TOP QUERIES BY DISK I/O USAGE",
   "type": "graph",
   "description": "Top statements by disk I/O utilization per database",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "percent", "label": "percents" }
   ],
   "targets": [
    {
     "expr": "sql_pg_stat_statements_disk_io_usage{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\"}",
     "legendFormat": "{{ datname }} : {{ query }}"
    }
   ]
  },
  {
   "title": "TOP BIGGEST TABLES / MATVIEWS",
   "type": "table",
   "description": "The largest tables / materialized views per database",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "max by (database, relname) (sql_pg_stat_user_tables_size{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", database=~\"[[database]]\"})"
    }
   ]
  },
  {
   "title": "TOP BIGGEST INDEXES",
   "type": "table",
   "description": "The largest indexes per database",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 83 },
   "targets": [
    {
     "expr": "max by (database, relname) (sql_pg_stat_user_indexes_size{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", database=~\"[[database]]\"})"
    }
   ]
  },
  {
   "title": "TOP UNUSED INDEXES",
   "type": "table",
   "description": "The biggest unused indexes per database",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 83 },
   "targets": [
    {
     "expr": "max by (database, index) (sql_pg_stat_user_indexes_unused{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", database=~\"[[database]]\"})"
    }
   ]
  },
  {
   "title": "TOP BLOATED TABLES",
   "type": "table",
   "description": "The most bloated tables / materialized views per database",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "max by (database, relname) (sql_pg_stat_user_tables_bloated{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", database=~\"[[database]]\", col=\"wasted_bytes\"})"
    },
    {
     "expr": "max by (database, relname) (sql_pg_stat_user_tables_bloated{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", database=~\"[[database]]\", col=\"wasted_ratio\"})"
    }
   ]
  },
  {
   "title": "TOP BLOATED INDEXES",
   "type": "table",
   "description": "The most bloated indexes per database",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 89 },
   "targets": [
    {
     "expr": "max by (database, index) (sql_pg_stat_user_indexes_bloated{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", database=~\"[[database]]\", col=\"wasted_bytes\"})\n\n"
    },
    {
     "expr": "max by (database, index) (sql_pg_stat_user_indexes_bloated{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", database=~\"[[database]]\", col=\"wasted_ratio\"})"
    }
   ]
  },
  {
   "title": "TOP FREQUENT FUNCTIONS",
   "type": "table",
   "description": "Top frequently used functions",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 89 },
   "targets": [
    {
     "expr": "max by (datname, funcname) (sql_pg_stat_user_functions{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\", col=\"calls\"})"
    },
    {
     "expr": "max by (datname, funcname) (sql_pg_stat_user_functions{job=~\"[[job_name]]\", host=~\"[[instance]]:[0-9]+\", datname=~\"[[database]]\", col=\"total_time\"})"
    }
   ]
  }
 ]
}